In [1]:
import numpy as np

# Creating a 1D array
x = np.array([1, 2, 3])

# Creating a 2D array
y = np.array([[1, 2], [3, 4]])

# Creating a 3D array
z = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(x)
print(y)
print(z)

[1 2 3]
[[1 2]
 [3 4]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
import numpy as np

a1_zeros = np.zeros((3, 3))
a2_ones = np.ones((2, 2))
a3_range = np.arange(0, 10, 2)

print("Array of 3x3")
print(a1_zeros)
print("Array of 2x2")
print(a2_ones)
print("Array of 1x1 0 to 8")
print(a3_range)

Array of 3x3
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array of 2x2
[[1. 1.]
 [1. 1.]]
Array of 1x1 0 to 8
[0 2 4 6 8]


In [4]:
import numpy as np

# Create a 1D array
arr1d = np.array([10, 20, 30, 40, 50])

# Single element access
print("Single element access:", arr1d[2])  

# Negative indexing
print("Negative indexing:", arr1d[-1])  

# Create a 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Multidimensional array access
print("Multidimensional array access:", arr2d[1, 0])

Single element access: 30
Negative indexing: 50
Multidimensional array access: 4


In [5]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
#elements from index 1 to 3
print("Range of Elements:",arr[1:4])

#all rows, second column
print("Multidimensional Slicing:", arr[:, 1])

Range of Elements: [[4 5 6]]
Multidimensional Slicing: [2 5]


In [9]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Integer array indexing 
indices = np.array([1, 3, 5])
print ("Integer array indexing:", arr[indices]) #arr[1],arr[3], arr[5]

# boolean array indexing 
cond = arr > 0
print ("\nElements greater than 0:\n", arr[cond])

Integer array indexing: [20 40 60]

Elements greater than 0:
 [ 10  20  30  40  50  60  70  80  90 100]


In [10]:
import numpy as np

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Addition
add = x + y  
print("Addition:",add)

# Subtraction
subtract = x - y 
print("substration:",subtract)

# Multiplication
multiply = x * y 
print("multiplication:",multiply)

# Division
divide = x / y  
print("division:", divide)

Addition: [5 7 9]
substration: [-3 -3 -3]
multiplication: [ 4 10 18]
division: [0.25 0.4  0.5 ]


In [11]:
import numpy as np

# Example array with both positive and negative values
arr = np.array([-3, -1, 0, 1, 3])

# Applying a unary operation: absolute value = means it must be >=0
result = np.absolute(arr)
print("Absolute value:", result)

Absolute value: [3 1 0 1 3]


In [12]:
import numpy as np

# Two example arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Applying a binary operation: addition
result = np.add(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)
print("Addition Result:", result)

Array 1: [1 2 3]
Array 2: [4 5 6]
Addition Result: [5 7 9]


In [13]:
#NumPy provides familiar mathematical functions such as sin, cos, exp, etc
import numpy as np

# create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("Sine values of array elements:", np.sin(a))

# exponential values
a = np.array([0, 1, 2, 3])
print ("Exponent of array elements:", np.exp(a))

# square root of array values
print ("Square root of array elements:", np.sqrt(a))

Sine values of array elements: [0.0000000e+00 1.0000000e+00 1.2246468e-16]
Exponent of array elements: [ 1.          2.71828183  7.3890561  20.08553692]
Square root of array elements: [0.         1.         1.41421356 1.73205081]


In [16]:
# We can use a simple np.sort() method for sorting Python NumPy arrays.
import numpy as np

# set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]

# Values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), 
           ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
           
# Creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n",
            np.sort(arr, order = 'name'))
            
print ("Array sorted by graduation year and then cgpa:\n",
                np.sort(arr, order = ['grad_year', 'cgpa']))

# NumPy structured arrays by default store fixed-length strings as byte strings, isiliye b dikh rha 
# if you want clean output the use 'U10'  in the place of 'S10'


Array sorted by names:
 [(b'Aakash', 2009, 9. ) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Pankaj', 2008, 7.9)]
Array sorted by graduation year and then cgpa:
 [(b'Pankaj', 2008, 7.9) (b'Ajay', 2008, 8.7) (b'Hrithik', 2009, 8.5)
 (b'Aakash', 2009, 9. )]


In [17]:
# Python program to demonstrate
# basic array characteristics
import numpy as np

# Creating array object
arr = np.array( [[ 1, 2, 3],
                [ 4, 2, 5]] )

# Printing type of arr object
print("Array is of type: ", type(arr))

# Printing array dimensions (axes)
print("No. of dimensions: ", arr.ndim)

# Printing shape of array
print("Shape of array: ", arr.shape)

# Printing size (total number of elements) of array
print("Size of array: ", arr.size)

# Printing type of elements in array
print("Array stores elements of type: ", arr.dtype)

Array is of type:  <class 'numpy.ndarray'>
No. of dimensions:  2
Shape of array:  (2, 3)
Size of array:  6
Array stores elements of type:  int64


In [18]:
import numpy as np

list_1 = [1, 2, 3, 4]

sample_array = np.array(list)

print("List in python : ", list)

print("Numpy Array in python :",
      sample_array)

List in python :  <class 'list'>
Numpy Array in python : <class 'list'>


In [19]:
print(type(list_1))

print(type(sample_array))

<class 'list'>
<class 'numpy.ndarray'>


In [20]:
import numpy as np

list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
list_3 = [9, 10, 11, 12]

sample_array = np.array([list_1, 
                         list_2,
                         list_3])
print("Numpy multi dimensional array in python\n",
      sample_array)

Numpy multi dimensional array in python
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [21]:
import numpy as np
sample_array = np.array([[0, 4, 2],
                       [3, 4, 5],
                       [23, 4, 5],
                       [2, 34, 5],
                       [5, 6, 7]])

print("shape of the array :",
      sample_array.shape)

shape of the array : (5, 3)


In [22]:
import numpy as np

sample_array_1 = np.array([[0, 4, 2]])

sample_array_2 = np.array([0.2, 0.4, 2.4])

print("Data type of the array 1 :",
      sample_array_1.dtype)

print("Data type of array 2 :",
      sample_array_2.dtype)

Data type of the array 1 : int64
Data type of array 2 : float64


In [23]:
import numpy as np

arr = np.array([3,4,5,5])

print("Array :",arr)

Array : [3 4 5 5]


In [24]:
import numpy as np

var = "Geekforgeeks"

arr = np.fromiter(var, dtype = 'U2')

print("fromiter() array :",arr)

fromiter() array : ['G' 'e' 'e' 'k' 'f' 'o' 'r' 'g' 'e' 'e' 'k' 's']


In [25]:
import numpy as np

np.arange(1, 20 , 2, dtype = np.float32)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.], dtype=float32)

In [26]:
import numpy as np

np.linspace(3.5, 10, 3, 
            dtype = np.int32)

array([ 3,  6, 10], dtype=int32)

In [27]:
import numpy as np

np.empty([4, 3],
         dtype = np.int32,
         order = 'f')

array([[1, 3, 2],
       [0, 0, 0],
       [2, 4, 5],
       [0, 0, 0]], dtype=int32)

In [28]:
import numpy as np

np.ones([4, 3],
        dtype = np.int32,
        order = 'f')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [29]:
import numpy as np
np.zeros([4, 3], 
         dtype = np.int32,
         order = 'f')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [30]:
import numpy as np

zeros_array = np.zeros((2, 3))
ones_array = np.ones((3, 3))
constant_array = np.full((2, 2), 7)
range_array = np.arange(0, 10, 2)  # start, stop, step
linspace_array = np.linspace(0, 1, 5)  # start, stop, num

print("Zero Array:","\n",zeros_array)
print("Ones Array:","\n",ones_array)
print("Constant Array:","\n",constant_array)
print("Range Array:","\n",range_array)
print("Linspace Array:","\n",linspace_array)

Zero Array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones Array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Constant Array: 
 [[7 7]
 [7 7]]
Range Array: 
 [0 2 4 6 8]
Linspace Array: 
 [0.   0.25 0.5  0.75 1.  ]


In [31]:
import numpy as np

random_array = np.random.rand(2, 3)
normal_array = np.random.randn(2, 2)
randint_array = np.random.randint(1, 10, size=(2, 3))  

print(random_array)
print(normal_array)
print(randint_array)

[[0.02760504 0.6247808  0.84743562]
 [0.15279878 0.11785099 0.54882874]]
[[-0.66640082 -0.84969616]
 [-1.14477038  0.45573457]]
[[2 7 3]
 [2 4 5]]


In [32]:
import numpy as np

identity_matrix = np.eye(3)
diagonal_array = np.diag([1, 2, 3])
zeros_like_array = np.zeros_like(diagonal_array)
ones_like_array = np.ones_like(diagonal_array)

print(identity_matrix)
print(diagonal_array)
print(zeros_like_array)
print(ones_like_array)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [39]:
# Accessing Elements in 1D Arrays
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])

10


In [40]:
# Accessing Elements in Multidimensional Arrays
import numpy as np 

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[1, 2])

6


In [41]:
# We can access elements by specifying row, column and depth indices like matrix[depth, row, column].
import numpy as np

cube = np.array([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])

print(cube[1, 2, 0])

16


In [42]:
# Slicing Arrays
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])

print(arr[1:4])

[1 2 3]


In [37]:
# Slicing Multidimensional Arrays
import numpy as np

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(matrix[0:2, 1:3])

[[2 3]
 [5 6]]


In [43]:
# Boolean Indexing
import numpy as np

arr = np.array([10, 15, 20, 25, 30])

print(arr[arr > 20])

[25 30]


In [44]:
#Fancy Indexing
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
indices = [0, 2, 4]
print(arr[indices])

[10 30 50]


In [50]:
# NumPy Array Broadcasting

# Broadcasting in NumPy allows us to perform 
# arithmetic operations on arrays of different shapes without reshaping them. 
# It automatically adjusts the smaller array to match the larger arrays shape by replicating its values along the necessary dimensions.
# This makes element-wise operations more efficient by reducing memory usage and eliminating the need for loops. 

In [51]:
# Numpy | Linear Algebra

# Importing numpy as np
import numpy as np
 
A = np.array([[6, 1, 1],
              [4, -2, 5],
              [2, 8, 7]])
 
# Rank of a matrix
print("Rank of A:", np.linalg.matrix_rank(A))
 
# Trace of matrix A
print("\nTrace of A:", np.trace(A))
 
# Determinant of a matrix
print("\nDeterminant of A:", np.linalg.det(A))
 
# Inverse of matrix A
print("\nInverse of A:\n", np.linalg.inv(A))
 
print("\nMatrix A raised to power 3:\n",
           np.linalg.matrix_power(A, 3))

Rank of A: 3

Trace of A: 11

Determinant of A: -306.0

Inverse of A:
 [[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]

Matrix A raised to power 3:
 [[336 162 228]
 [406 162 469]
 [698 702 905]]


In [52]:
import numpy as np
from numpy import linalg as geek

# Creating an array using array function
a = np.array([[1, -2j], [2j, 5]])

print("Array is:", a)

# Calculating eigenvalues and eigenvectors using eigh() function
c, d = geek.eigh(a)

print("Eigenvalues are:", c)
print("Eigenvectors are:", d)

Array is: [[ 1.+0.j -0.-2.j]
 [ 0.+2.j  5.+0.j]]
Eigenvalues are: [0.17157288 5.82842712]
Eigenvectors are: [[-0.92387953+0.j         -0.38268343+0.j        ]
 [ 0.        +0.38268343j  0.        -0.92387953j]]


In [53]:
# Python Program illustrating
# numpy.dot() method
 
import numpy as geek
 
# Scalars
product = geek.dot(5, 4)
print("Dot Product of scalar values  : ", product)
 
# 1D array
vector_a = 2 + 3j
vector_b = 4 + 5j
 
product = geek.dot(vector_a, vector_b)
print("Dot Product  : ", product)

Dot Product of scalar values  :  20
Dot Product  :  (-7+22j)


In [54]:
# Q create a 5*5 matrix with values 1 to 25
import numpy as np

# create 1D array from 1 to 25
arr = np.arange(1, 26)

# reshape into 5x5 matrix
matrix = arr.reshape(5, 5)

print(matrix)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [55]:
mid = matrix[1:4,1:4]
print("Middle value is 3x3: \n", mid)

Middle value is 3x3: 
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [56]:
row_sum=np.sum(matrix, axis=1)
print("Row wise sum is: \n",row_sum)

Row wise sum is: 
 [ 15  40  65  90 115]


In [57]:
col_sum=np.sum(matrix, axis=0)
print("Coloumn wise sum is: \n",col_sum)

Coloumn wise sum is: 
 [55 60 65 70 75]
